currency_regex: !ruby/regexp /\A[+-]?(\d+\.\d+)?\Z/
product:
  max_length_name: 100
  min_discount: 0
  max_discount: 100
  max_residual: 5000
length:
  max_length_email: 150
  min_length_username: 6
  max_length_username: 50
  min_length_password: 6
size:
  page_record_medium: 6
admin:
  order_status:
    pending: 0
    accept: 1
    cancel: 2
    reject_: 3
  order_option:
    oldest: "0"
    newest: "1"
    status: "2"
  product_option:
    oldest: "0"
    newest: "1"
    price: "2"
  product:
    image:
      format: ["image/png", "image/jpg", "image/jpeg"]
      less_than: 5
      width: 70
      height: 70
      width_200: 200
      height_200: 200
